language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
after_success:
    - 'npm install coveralls &&./node_modules/.bin/jest --coverage && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'
